[project]
name = "neural-network-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.1.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
